[versions]
agp = "8.3.0-alpha03"
converter-gson = "2.9.0"
dagger-android = "2.46.1"
glide = "4.15.1"
gson = "2.10.1"
instabug = "12.9.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
leakcanary-android = "2.11"
logging-interceptor = "5.0.0-alpha.11"
material = "1.11.0"
constraintlayout = "2.1.4"
navigation-ui = "2.7.7"
recyclerview = "1.3.2"
room-runtime = "2.6.1"
rxandroid = "3.0.2"
rxjava = "3.1.8"
security-crypto = "1.1.0-alpha06"
skeletonlayout = "5.0.0"
swiperefreshlayout = "1.1.0"
work-runtime = "2.9.0"
work-rxjava3 = "2.7.1"

[libraries]
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation-ui" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigation-ui" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-runtime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
androidx-room-rxjava3 = { module = "androidx.room:room-rxjava3", version.ref = "room-runtime" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "work-runtime" }
androidx-work-rxjava3 = { module = "androidx.work:work-rxjava3", version.ref = "work-rxjava3" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converter-gson" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger-android" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger-android" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger-android" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger-android" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
instabug = { module = "com.instabug.library:instabug", version.ref = "instabug" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary-android" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converter-gson" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
skeletonlayout = { module = "com.faltenreich:skeletonlayout", version.ref = "skeletonlayout" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

